Using /home/kgluza/Manufacturo/semaphore/ansible-for-semaphore/ansible.cfg as config file
...ERROR! the role 'self_service_refresh' was not found in /home/kgluza/Manufacturo/semaphore/ansible-for-semaphore/playbooks/roles:/home/kgluza/Manufacturo/semaphore/roles:/home/kgluza/Manufacturo/semaphore/ansible-for-semaphore/playbooks

The error appears to be in '/home/kgluza/Manufacturo/semaphore/ansible-for-semaphore/playbooks/self_service_refresh.yaml': line 130, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      ansible.builtin.include_role:
        name: self_service_refresh
              ^ here
.

[1m# STATS *******************************************************************************************************************[0m
[0;32mlocalhost    : ok=3	changed=0	failed=0	unreachable=0	rescued=0	ignored=0[0m
